---
title: "Project Proposal"
author: "Patrick McHugh and Nick Mandarano"
date: "3/31/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Proposal

We are both interested in basketball, and chose to do an NBA-related project. Not surprisingly, we are not the only people interested in basketball, and countless statistical analyses of basketball data have been done on a plethora of platforms with a variety of goals. We attempted to come up with an original approach and decided to fit a regression model for salary of NBA players, using statistics and other information about the players as covariates.

Our data includes many seasonal statistics for each player, including simple stats like points, rebounds, and assists, as well as a variety of advanced metrics such as True Shooting % and Box +/-. We also have access to some personal information for each player, such as team, position, height, weight, age, race, place of birth, college attended, and salary. We noticed some apparent inaccuracies in the race variable but all others will be under consideration for the model.

We had access to data from many years, but chose to use only data from the most recent NBA season in the dataset, 2015-16, to avoid the need for a mixed effects model that would arise from using multiple seasons due to the heavy correlation between the observations from one player across different seasons.

Salary is known before the season starts and statistics are created, so it is not a response variable in the traditional sense of a causal effect. Our regression project attempts to explore the relationship between salary and the covariates. We are interested in how information from several areas, including basic statistics like points, advanced statistics like Value Over Replacement Player, and personal information such as height, relate to salary, individually and collectively. We will also aim to prescribe a true mean function, and identify players who may be overperforming or underperforming their contract according to the 2015-16 market; i.e., putting up better or worse statistics than one might expect a player on their salary to do.

